################# English language ################
[en]
languageName = "English"
languageCode = "en-US"
contentDir = "content/english"
weight = 1

################# German language ################
[de]
languageName = "Deutsch"
languageCode = "de-DE"
contentDir = "content/german"
weight = 2