#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.png"
# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "150px"
# logo text will only show when logo is missing.
logo_text = "Songlaa"
# navbar fixed to top
navbar_fixed = false
# OpenGraph / Twitter Card metadata
description = "Expert-led, hands-on Kubernetes and cloud native security trainings designed for professionals and teams"
author = "Songlaa"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own

# Social media and SEO
keywords = "kubernetes training, kubernetes security, cloud native security, docker training, container security, DevSecOps, cybersecurity training"
# Whether to display text descriptors (like "E-mail: ", "Phone: ") before the address block elements
address_descriptors = false

# Navigation
[navigation]
brand = "Songlaa"
home = "Home"
work = "Trainings"
testimonials = "Testimonials"
services = "Services"
about = "About"
contact = "Contact"

# Hero section
[hero]
title = "Kubernetes, Kubernetes Security & Cloud Native Security Trainings"
subtitle = "Expert-led, hands-on trainings designed for professionals and teams."

# Intro section - Our training programs
[intro]

[[intro.item]]
title = "Kubernetes Fundamentals"
description = "Learn Kubernetes from the ground up — with security woven in from the very first pod to a production-ready cluster, through engaging, hands-on exercises."
url = "#fh5co-kubernetes-fundamentals"
button = "Learn More"
icon = "icon-settings"
img = "img_7.jpg"

[[intro.item]]
title = "Kubernetes Security"
description = "Master Kubernetes with a hands-on focus on security — from network policies to runtime protection, with a strong emphasis on practical labs."
url = "#fh5co-kubernetes-security"
button = "Learn More"
icon = "icon-shield"
img = "img_8.jpg"

[[intro.item]]
title = "Custom Security Training"
description = "Get a fully tailored security training program for Cloud Native Technologies, designed around your needs — complete with immersive hands-on labs."
url = "#fh5co-contact"
button = "Learn More"
icon = "icon-wrench"
img = "img_8.jpg"

# contact info
email = "notavailable"
location = """
**Songlaa GmbH**  
Bern, Switzerland
"""
# copyright
copyright = "© 2025 Songlaa GmbH. All rights reserved."
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= ""
# google tag manager, see https://developers.google.com/tag-manager/
google_tag_manager = "" # example: G-XXXXXXXXXX

# Training sections for the homepage
[kubernetes_fundamentals]
enable = true

[kubernetes_security] 
enable = true



############################# social site ########################
[[social]]
title = "github"
icon = "fab fa-github" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://github.com/songlaa"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.linkedin.com/in/gabriel-graf-6b6446319"
# recaptch v3 site key
recaptcha_site_key = "xxx-xxxxxxxxxxxxxxxxxxxxxxxx"

# Contact section
[contact]
enable = true
title = "Get in Touch"
description = "Ready to enhance your team's Kubernetes and cloud native security skills? Let's discuss your training needs."
info = "Contact Information"
button = "Send Message"

[[contact.details]]
icon = "icon-location-pin"
info = """**Songlaa GmbH**  
Bern, Switzerland"""

[[contact.details]]
icon = "icon-social-linkedin"
info = """**LinkedIn**  
[Connect here](https://www.linkedin.com/in/gabriel-graf-6b6446319)"""

[contact.form]
enable = true
# FormSubmit.co action URL
action = "https://formsubmit.co/7fe3785ae223b6189369b2545fde329e"
# Image on custom success page `/message_sent.html`
success_image = "images/paper-plane.svg"


# Preloader
[preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "get a quote"
link = "#fh5co-contact"

