#################### German parameters ################################
# Favicon
favicon = "images/favicon.png"
# Logo
logo = "images/logo.png"
logo_width = "150px"
logo_text = "Songlaa"
navbar_fixed = false
# OpenGraph / Twitter Card metadata
description = "Expertengeleitet, praxisorientierte Kubernetes- und Cloud Native Security-Schulungen für Profis und Teams"
author = "Songlaa"
image = "images/logo.png"

# Social media and SEO
keywords = "kubernetes schulung, kubernetes sicherheit, cloud native sicherheit, docker schulung, container sicherheit, DevSecOps, cybersecurity schulung"
address_descriptors = false

# Navigation (Keep English) - match base params.toml exactly
[navigation]
brand = "Songlaa"
home = "Home"
contact = "Contact"

# Hero section (German)
[hero]
title = "Kubernetes, Kubernetes Sicherheit & Cloud Native Security Schulungen"
subtitle = "Expertengeleitet, praxisorientierte Schulungen für Profis und Teams."

# Intro section (German)
[intro]

[[intro.item]]
title = "Kubernetes Grundlagen"
description = "Lernen Sie Kubernetes von Grund auf — mit Sicherheit von der ersten Pod bis zum produktionsreifen Cluster durch ansprechende, praxisorientierte Übungen."
url = "#fh5co-kubernetes-fundamentals"
button = "Mehr erfahren"
icon = "icon-settings"
img = "img_7.jpg"

[[intro.item]]
title = "Kubernetes Sicherheit"
description = "Meistern Sie Kubernetes mit praktischem Fokus auf Sicherheit — von Netzwerk-Policies bis zum Laufzeit-Schutz mit starkem Fokus auf praktische Übungen."
url = "#fh5co-kubernetes-security"
button = "Mehr erfahren"
icon = "icon-shield"
img = "img_8.jpg"

[[intro.item]]
title = "Individuelle Sicherheitsschulung"
description = "Erhalten Sie ein vollständig maßgeschneidertes Sicherheitsschulungsprogramm für Cloud Native Technologien, designed um Ihre Bedürfnisse — komplett mit immersiven praktischen Übungen."
url = "#fh5co-contact"
button = "Mehr erfahren"
icon = "icon-wrench"
img = "img_8.jpg"

# Contact info
email = "notavailable"
location = """
**Songlaa GmbH**  
Bern, Schweiz
"""
copyright = "© 2025 Songlaa GmbH. Alle Rechte vorbehalten."
custom_script= ""
google_tag_manager = ""

# Training sections - match English page exactly
[kubernetes_fundamentals]
enable = true

[kubernetes_security] 
enable = true

# Social sites
[[social]]
title = "github"
icon = "fab fa-github"
link = "https://github.com/songlaa"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/in/gabriel-graf-6b6446319"

recaptcha_site_key = "xxx-xxxxxxxxxxxxxxxxxxxxxxxx"

# Contact section (German content, English title)
[contact]
enable = true
title = "Get in Touch"
description = "Bereit, die Kubernetes- und Cloud Native Security-Fähigkeiten Ihres Teams zu erweitern? Lassen Sie uns über Ihre Schulungsbedürfnisse sprechen."
info = "Kontaktinformationen"
button = "Nachricht senden"

[[contact.details]]
icon = "icon-location-pin"
info = """**Songlaa GmbH**  
Bern, Schweiz"""

[[contact.details]]
icon = "icon-social-linkedin"
info = """**LinkedIn**  
[Hier verbinden](https://www.linkedin.com/in/gabriel-graf-6b6446319)"""

[contact.form]
enable = true
action = "https://formsubmit.co/7fe3785ae223b6189369b2545fde329e"
success_image = "images/paper-plane.svg"

# Preloader
[preloader]
enable = true
preloader = ""

# Navigation button (Keep English)
[navigation_button]
enable = true
label = "get a quote"
link = "#fh5co-contact"